# Generated by Django 2.1.2 on 2018-12-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='vedio',
            new_name='video',
        ),
    ]
