# Generated by Django 2.1.2 on 2018-12-08 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20181204_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 8, 38, 24, 955296, tzinfo=utc)),
        ),
    ]
