# Generated by Django 2.1.2 on 2018-12-08 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20181208_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 12, 39, 26, 290170, tzinfo=utc)),
        ),
    ]
