# Generated by Django 2.1.2 on 2019-02-16 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0013_auto_20181211_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applaud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('applauder', models.ForeignKey(on_delete='CASCADE', related_name='applauds', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete='CASCADE', related_name='applauds', to='article.ArticlePost')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
