# Generated by Django 2.1.2 on 2019-02-16 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0014_applaud'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applaud',
            unique_together={('article', 'applauder')},
        ),
    ]
